// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJzih9nIS2gpWJLcMEWghu7V0sdORdAGg',
    appId: '1:274704029989:web:3ce6c7adef19547d4362cc',
    messagingSenderId: '274704029989',
    projectId: 'nut-app-c6d05',
    authDomain: 'nut-app-c6d05.firebaseapp.com',
    storageBucket: 'nut-app-c6d05.appspot.com',
    measurementId: 'G-XGXXGZQBND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5InRHXTw6-LFvPuq_e1m3fpWKHCbO9Q',
    appId: '1:274704029989:android:ec4527770623cbe44362cc',
    messagingSenderId: '274704029989',
    projectId: 'nut-app-c6d05',
    storageBucket: 'nut-app-c6d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO2xt5F_p9t94e6TybUBWw94PjqF01Jf4',
    appId: '1:274704029989:ios:4d16d05912b15b184362cc',
    messagingSenderId: '274704029989',
    projectId: 'nut-app-c6d05',
    storageBucket: 'nut-app-c6d05.appspot.com',
    iosClientId: '274704029989-qloi0v09dlif5508egs7t8v0j5an6opa.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutAppAndrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO2xt5F_p9t94e6TybUBWw94PjqF01Jf4',
    appId: '1:274704029989:ios:4d16d05912b15b184362cc',
    messagingSenderId: '274704029989',
    projectId: 'nut-app-c6d05',
    storageBucket: 'nut-app-c6d05.appspot.com',
    iosClientId: '274704029989-qloi0v09dlif5508egs7t8v0j5an6opa.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutAppAndrew',
  );
}
